databases:
  source:
    database: "postgres"
    hostname: "postgres"
    username: "postgres"
    password: "root"
    port: 5432
  target:
    database: "pagarme"
    hostname: "postgres"
    username: "root"
    password: "root"
    port: 5432
