version: '2'

volumes:
  goroot: {}

services:
  test:
    build: .
    command: go test ./...
    volumes:
      - .:/go/src/github.com/pagarme/teleport/

  source:
    build: .
    command: teleport -config source_config.yml
    volumes:
      - .:/go/src/github.com/pagarme/teleport/
    ports:
      - 3000:3000

  target:
    build: .
    command: teleport -config target_config.yml
    volumes:
      - .:/go/src/github.com/pagarme/teleport/
    ports:
      - 3001:3001

  # Databases
  postgres:
    image: postgres:9.4
    volumes:
        - .:/code
