version: '2'

volumes:
  goroot: {}

services:
  common:
    build: .
    command: go run main.go
    volumes:
      - goroot:/go
      - .:/go/src/github.com/pagarme/teleport/
    ports:
      - 3000:3000

  # Databases
  postgres:
    image: postgres:9.4
    volumes:
        - .:/code
