batch_size: 10000
processing_interval: 100
database:
  name: "finops-db"
  database: "postgres"
  hostname: "postgres"
  username: "postgres"
  password: "root"
  port: 5432
server:
  hostname: "0.0.0.0"
  port: 3000
  # auth: asd
targets:
  tar:
    target_expression: "public.*"
    endpoint:
      hostname: "target"
      port: 3001
    apply_schema: "public"
