batch_size: 10000
processing_intervals:
  batcher: 100
  transmitter: 100
  applier: 100
  vacuum: 500
  ddlwatcher: 5000
database:
  name: "finops-db"
  database: "postgres"
  hostname: "postgres"
  username: "postgres"
  password: "root"
  port: 5432
  options:
    sslmode: disable
server:
  hostname: "0.0.0.0"
  port: 3000
  # auth: asd
targets:
  tar:
    target_expression: "public.*"
    endpoint:
      hostname: "target"
      port: 3001
    apply_schema: "test"
